name: "QuickBooks guMCP Server"
icon: "assets/icon.png"
description: "Interact with QuickBooks Online for accounting and financial management"
documentation_path: "README.md"
tools:
  - name: "search_customers"
    description: "Search for customers by name, email, or phone"
  - name: "analyze_sred"
    description: "Analyze expenses for potential SR&ED eligibility"
  - name: "analyze_cash_flow"
    description: "Analyze cash flow trends and patterns"
  - name: "find_duplicate_transactions"
    description: "Identify potential duplicate transactions"
  - name: "analyze_customer_payment_patterns"
    description: "Analyze customer payment behavior"
  - name: "generate_financial_metrics"
    description: "Generate key financial metrics and ratios" 