name: "Figma guMCP Server"
icon: "assets/icon.png"
description: "Interact with Figma files, comments, and projects using the Figma API"
documentation_path: "README.md"
tools:
  - name: "get_me"
    description: "Get the authenticated user's information including ID, handle, and email"
  - name: "get_file"
    description: "Get a Figma file by key, including its structure and content"
  - name: "get_file_comments"
    description: "Get all comments for a specific Figma file"
  - name: "post_comment"
    description: "Add a new comment to a Figma file"
  - name: "delete_comment"
    description: "Remove a comment from a Figma file"
  - name: "get_comment_reactions"
    description: "Get all reactions for a specific comment"
  - name: "post_comment_reaction"
    description: "Add a reaction to a comment"
  - name: "delete_comment_reaction"
    description: "Remove a reaction from a comment"
  - name: "get_team_projects"
    description: "List all projects within a team"
  - name: "get_project_files"
    description: "List all files within a project"
  - name: "get_file_versions"
    description: "Get version history of a file"
