name: "Apify GuMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with the Apify API"
documentation_path: "README.md"
tools:
  # Actors
  - name: "create_actor"
    description: "Create a new Actor"
  - name: "build_actor"
    description: "Build an Actor from source code"
  - name: "list_actors"
    description: "List all Actors"
  - name: "get_actor"
    description: "Get metadata for one Actor"
  - name: "delete_actor"
    description: "Delete an Actor"
  - name: "run_actor"
    description: "Start an Actor run asynchronously"
  - name: "list_actor_runs"
    description: "List runs for an Actor"
  # Tasks
  - name: "list_tasks"
    description: "List all Tasks"
  - name: "get_task"
    description: "Get a Task"
  - name: "create_task"
    description: "Create a new Task"
  - name: "update_task"
    description: "Update an existing Task"
  - name: "delete_task"
    description: "Delete a Task"
  - name: "update_task_input"
    description: "Update input for a Task"
  - name: "run_task"
    description: "Run a Task"
  - name: "list_task_runs"
    description: "List runs for a Task"
  # Datasets
  - name: "list_datasets"
    description: "List all Datasets"
  - name: "delete_dataset"
    description: "Delete a Dataset" 