name: "Calendly guMCP Server"
icon: "assets/icon.png"
description: "Interact with Calendly scheduling and event management"
documentation_path: "README.md"
tools:
  - name: "list_event_types"
    description: "List all available event types (meeting templates)"
  - name: "get_availability"
    description: "Get available time slots for a specific event type"
  - name: "list_scheduled_events"
    description: "List scheduled events in a given time range"
  - name: "cancel_event"
    description: "Cancel a scheduled event"
  - name: "create_scheduling_link"
    description: "Create a single-use scheduling link for a specific event type"
