name: "YouTube guMCP Server"
icon: "assets/icon.png"
description: "Interact with YouTube videos, channels, and playlists using the YouTube Data API"
documentation_path: "README.md"
tools:
  - name: "get_video_details"
    description: "Get title, description, and duration of a video by ID"
  - name: "list_channel_videos"
    description: "List recent videos uploaded by a channel"
  - name: "get_video_statistics"
    description: "Fetch view count, likes, and comments of a video"
  - name: "search_videos"
    description: "Search for videos across YouTube"
  - name: "get_channel_details"
    description: "Retrieve channel metadata including title and description"
  - name: "list_channel_playlists"
    description: "List playlists created by a specific channel"
  - name: "get_channel_statistics"
    description: "Get subscriber count, view count, and other channel stats"
  - name: "list_playlist_items"
    description: "List videos inside a specified playlist"
  - name: "get_playlist_details"
    description: "Fetch metadata about a playlist (title, description, etc.)"
