name: "Hacker News MCP Server"
icon: "assets/icon.png"
description: "Interact with Hacker News using the Hacker News API"
documentation_path: "README.md"
tools:
  - name: "get_top_stories"
    description: "Get the top stories from Hacker News"
  - name: "get_latest_posts"
    description: "Get the latest stories from Hacker News with optional limit"
  - name: "get_story_details"
    description: "Get the details of a specific story from Hacker News using the story id."
  - name: "get_comments"
    description: "Get the comments of a specific story from Hacker News using the story id."
  - name: "get_user"
    description: "Get the details of a specific user from Hacker News using the username."
  - name: "get_stories_by_type"
    description: "Get stories by type (top, new, best, ask, show, job)"