name: "Stripe guMCP Server"
icon: "assets/icon.png"
description: "Interact with Stripe for customer management, subscriptions, payments, invoices, and more."
documentation_path: "README.md"
tools:
  - name: "list_customers"
    description: "List all Stripe customers"
  - name: "retrieve_balance"
    description: "Retrieve the current Stripe account balance"
  - name: "list_subscriptions"
    description: "List all subscriptions in the Stripe account"
  - name: "create_payment_intent"
    description: "Create a new payment intent with specified amount and currency"
  - name: "update_subscription"
    description: "Update metadata or attributes of a Stripe subscription"
  - name: "list_payment_intents"
    description: "List all payment intents"
  - name: "list_charges"
    description: "List all charges processed by the Stripe account"
  - name: "create_customer"
    description: "Create a new customer in Stripe"
  - name: "create_invoice"
    description: "Create a new draft invoice for a specified customer"
  - name: "list_invoices"
    description: "List all invoices created in Stripe"
  - name: "retrieve_customer"
    description: "Retrieve details of a specific customer by ID"
  - name: "create_product"
    description: "Create a new product to be sold or subscribed to"
  - name: "confirm_payment_intent"
    description: "Confirm a payment intent with a given ID"
  - name: "list_products"
    description: "List all available products in Stripe"
  - name: "cancel_subscription"
    description: "Cancel a subscription by ID"
  - name: "retrieve_subscription"
    description: "Retrieve a subscription by its ID"
  - name: "create_price"
    description: "Create a price object for a product, recurring or one-time"
  - name: "create_subscription"
    description: "Create a subscription for a customer with a price"
  - name: "update_customer"
    description: "Update customer attributes such as name, email, etc."
