name: "PagerDuty guMCP Server"
icon: "assets/icon.png"
description: "Interact with PagerDuty incident management and on-call scheduling"
documentation_path: "README.md"
tools:
  - name: "get_user"
    description: "Get details about an existing user in PagerDuty"
  - name: "list_incidents"
    description: "List existing incidents from PagerDuty"
  - name: "list_services"
    description: "List existing services from PagerDuty"
  - name: "list_schedules"
    description: "List on-call schedules from PagerDuty"
  - name: "create_schedule"
    description: "Create a new on-call schedule in PagerDuty"
  - name: "get_schedule"
    description: "Get details about an existing schedule in PagerDuty"
  - name: "delete_schedule"
    description: "Delete an on-call schedule in PagerDuty"
  - name: "list_oncalls"
    description: "List on-call entries from PagerDuty"
  - name: "list_notifications"
    description: "List notifications from PagerDuty"
