name: "SendGrid guMCP Server"
icon: "assets/icon.png"
description: "Interact with SendGrid email API for sending emails, managing templates, contacts, and more"
documentation_path: "README.md"
tools:
  - name: "send_email"
    description: "Send an email using SendGrid"
  - name: "get_email_stats"
    description: "Get email statistics from SendGrid"
  - name: "create_template"
    description: "Create a new email template"
  - name: "list_templates"
    description: "List all email templates"
  - name: "add_contact"
    description: "Add a contact to SendGrid"
  - name: "manage_suppression"
    description: "Add or remove email from suppression list"
