name: "Supabase guMCP Server"
icon: "assets/icon.png"
description: "Interact with Supabase for database, storage, and project management"
documentation_path: "README.md"
tools:
  # PROJECT MANAGEMENT TOOLS
  - name: "list_organizations"
    description: "List all Supabase organizations the user is a member of"
  - name: "list_projects"
    description: "Returns a list of all Supabase projects you've previously created"
  - name: "get_project"
    description: "Get details of a specific Supabase project by its reference ID"
  - name: "create_project"
    description: "Create a new Supabase project in an organization"
  # STORAGE MANAGEMENT TOOLS
  - name: "create_storage_bucket"
    description: "Create a new storage bucket in a Supabase project"
  - name: "list_storage_buckets"
    description: "List all storage buckets in a Supabase project"
  - name: "get_storage_bucket"
    description: "Get details about a specific storage bucket in a Supabase project"
  - name: "delete_storage_bucket"
    description: "Delete a storage bucket from a Supabase project"
