name: "OneDrive guMCP Server"
icon: "assets/icon.png"
description: "Manage files and folders in Microsoft OneDrive"
documentation_path: "README.md"
tools:
  - name: "list_files"
    description: "Lists files and folders in a OneDrive directory"
  - name: "upload_file"
    description: "Uploads a file to OneDrive"
  - name: "download_file"
    description: "Downloads a file from OneDrive"
  - name: "create_folder"
    description: "Creates a new folder in OneDrive"
  - name: "delete_item"
    description: "Deletes a file or folder from OneDrive"
  - name: "search_files"
    description: "Searches for files in OneDrive"
  - name: "get_file_sharing_link"
    description: "Gets sharing link for a OneDrive file"
