name: "Asana guMCP Server"
icon: "assets/icon.png"
description: "Interact with Asana workspaces, projects, tasks, and attachments using the Asana API"
documentation_path: "README.md"
tools:
  - name: "get_me"
    description: "Get the current user's information including ID, name, and email"
  - name: "get_workspaces"
    description: "Get all workspaces accessible to the user"
  - name: "get_projects"
    description: "Get all projects in a workspace"
  - name: "get_project"
    description: "Get a specific project by ID"
  - name: "create_project"
    description: "Create a new project in a workspace"
  - name: "update_project"
    description: "Update details of an existing project"
  - name: "get_tasks"
    description: "Get all tasks in a project"
  - name: "get_task"
    description: "Get a specific task by ID"
  - name: "create_task"
    description: "Create a new task in a project"
  - name: "update_task"
    description: "Update a task's details"
  - name: "delete_task"
    description: "Delete a task"
  - name: "get_users"
    description: "Get all users in a workspace"
  - name: "get_user"
    description: "Get a specific user by ID"
  - name: "duplicate_task"
    description: "Duplicate an existing task"
  - name: "add_follower_to_task"
    description: "Add a follower to a task"
  - name: "remove_follower_from_task"
    description: "Remove a follower from a task"
  - name: "mark_task_complete"
    description: "Mark a task as complete"
  - name: "mark_task_incomplete"
    description: "Mark a task as incomplete"
  - name: "add_subtask"
    description: "Add a subtask to an existing task"
  - name: "assign_task"
    description: "Assign a task to a user"
  - name: "unassign_task"
    description: "Remove the assignee from a task"
  - name: "add_task_to_project"
    description: "Add an existing task to a project"
  - name: "remove_task_from_project"
    description: "Remove a task from a project"
  - name: "create_section"
    description: "Create a new section in a project"
  - name: "add_task_to_section"
    description: "Add a task to a specific section"
  - name: "get_sections"
    description: "Get sections in a project, optionally filtered by name"
  - name: "delete_section"
    description: "Delete a specific section (must be empty and not the last section)"
  - name: "create_tag"
    description: "Create a new tag in a workspace or organization"
  - name: "get_tags"
    description: "Get tags in a workspace, optionally filtered by name"
  - name: "add_tag_to_task"
    description: "Add a tag to a task"
  - name: "remove_tag_from_task"
    description: "Remove a tag from a task"
  - name: "create_attachment"
    description: "Create an attachment for a task or other object"
