name: "PostHog guMCP Server"
icon: "assets/icon.png"
description: "Interact with PostHog analytics platform for event tracking, feature flags, and user management"
documentation_path: "README.md"
tools:
  # Actions Management
  - name: "list_actions"
    description: "List all actions in PostHog"
  - name: "create_action"
    description: "Create a new action in PostHog"
  - name: "get_action"
    description: "Get details of a specific action"
  - name: "update_action"
    description: "Update an existing action"

  # Event Tracking
  - name: "capture_event"
    description: "Capture a new event in PostHog"
  - name: "identify_user"
    description: "Identify a user with properties"
  - name: "group_identify"
    description: "Identify a group with properties"
  - name: "capture_group_event"
    description: "Capture an event for a group"

  # Feature Flags
  - name: "check_feature_flag"
    description: "Check if a feature flag is enabled"
  - name: "get_feature_flag_payload"
    description: "Get the payload for a feature flag"
  - name: "get_all_flags"
    description: "Get all feature flags"

  # Annotations
  - name: "list_annotations"
    description: "List all annotations"
  - name: "create_annotation"
    description: "Create a new annotation"
  - name: "get_annotation"
    description: "Get details of a specific annotation"
  - name: "update_annotation"
    description: "Update an existing annotation"

  # Cohorts
  - name: "list_cohorts"
    description: "List all cohorts"
  - name: "create_cohort"
    description: "Create a new cohort"
  - name: "get_cohort"
    description: "Get details of a specific cohort"
  - name: "update_cohort"
    description: "Update an existing cohort"
  - name: "delete_cohort"
    description: "Delete a cohort"

  # Dashboards
  - name: "list_dashboards"
    description: "List all dashboards"
  - name: "create_dashboard"
    description: "Create a new dashboard"
  - name: "get_dashboard"
    description: "Get details of a specific dashboard"
  - name: "update_dashboard"
    description: "Update an existing dashboard"
  - name: "delete_dashboard"
    description: "Delete a dashboard"
  - name: "list_dashboard_collaborators"
    description: "List collaborators for a dashboard"
  - name: "add_dashboard_collaborator"
    description: "Add a collaborator to a dashboard"
  - name: "get_dashboard_sharing"
    description: "Get sharing settings for a dashboard"

  # Persons
  - name: "list_persons"
    description: "List all persons"
  - name: "get_person"
    description: "Get details of a specific person"

  # Experiments
  - name: "list_experiments"
    description: "List all experiments"
  - name: "create_experiment"
    description: "Create a new experiment"
  - name: "get_experiment"
    description: "Get details of a specific experiment"
  - name: "update_experiment"
    description: "Update an existing experiment"
  - name: "check_experiments_requiring_flag"
    description: "Check experiments that require a feature flag"

  # Insights
  - name: "list_insights"
    description: "List all insights"
  - name: "create_insight"
    description: "Create a new insight"
  - name: "get_insight"
    description: "Get details of a specific insight"
  - name: "update_insight"
    description: "Update an existing insight"
  - name: "get_insight_sharing"
    description: "Get sharing settings for an insight"
  - name: "get_insight_activity"
    description: "Get activity for a specific insight"
  - name: "mark_insight_viewed"
    description: "Mark an insight as viewed"
  - name: "get_insights_activity"
    description: "Get activity for all insights"
  - name: "get_trend_insights"
    description: "Get trend insights"
  - name: "create_trend_insight"
    description: "Create a new trend insight"