name: "Patreon guMCP Server"
icon: "assets/icon.png"
description: "Interact with Patreon campaigns, posts, and members using the Patreon API"
documentation_path: "README.md"
tools:
  - name: "get_identity"
    description: "Get the current user's information with optional fields and includes"
  - name: "get_campaigns"
    description: "Get campaigns owned by the authorized user"
  - name: "get_campaign"
    description: "Get information about a single Campaign by ID"
  - name: "get_campaign_members"
    description: "Get members of a specific campaign"
  - name: "get_campaign_posts"
    description: "Get a list of all posts on a given campaign"
  - name: "get_post"
    description: "Get details of a specific post" 