name: "PowerPoint guMCP Server"
icon: "assets/icon.png"
description: "Interact with Microsoft PowerPoint presentations through OneDrive and SharePoint for creating, editing, and managing presentations"
documentation_path: "README.md"
tools:
  # PRESENTATION MANAGEMENT TOOLS
  - name: "list_presentations"
    description: "List PowerPoint presentations from OneDrive"
  - name: "create_presentation"
    description: "Create a new PowerPoint presentation in OneDrive"
  - name: "read_presentation"
    description: "Extract content/structure from a PowerPoint presentation"
  - name: "delete_presentation"
    description: "Delete a PowerPoint presentation from OneDrive"
  - name: "download_presentation"
    description: "Get a download URL for a PowerPoint presentation"
  - name: "search_presentations"
    description: "Search for PowerPoint presentations by content"
  # SLIDE MANAGEMENT TOOLS
  - name: "add_slide"
    description: "Add a new slide to an existing presentation"
  - name: "update_slide"
    description: "Update content on a specific slide"
  - name: "delete_slide"
    description: "Remove a slide from a presentation"
