name: "Salesforce guMCP Server"
icon: "assets/icon.png"
description: "Interact with Salesforce data and execute operations"
documentation_path: "README.md"
tools:
  - name: "soql_query"
    description: "Executes a SOQL query to retrieve Salesforce records with support for relationships and complex filters"
  - name: "sosl_search"
    description: "Performs a text-based search across multiple Salesforce objects using SOSL"
  - name: "describe_object"
    description: "Retrieves detailed metadata about a Salesforce object including fields, relationships, and permissions"
  - name: "get_record"
    description: "Retrieves a specific Salesforce record by ID with all accessible fields"
  - name: "create_record"
    description: "Creates a new record in Salesforce"
  - name: "update_record"
    description: "Updates an existing Salesforce record"
  - name: "delete_record"
    description: "Deletes a Salesforce record"
  - name: "get_org_limits"
    description: "Retrieves current organization limits and usage"
