name: "Shopify guMCP Server"
icon: "assets/icon.png"
description: "Interact with Shopify's Admin API using GraphQL"
documentation_path: "README.md"
tools:
  - name: "get_shop_details"
    description: "Gets the details of a shop in Shopify"
  - name: "create_product"
    description: "Creates a product on Shopify"
  - name: "get_products"
    description: "Retrieves a list of products from Shopify"
  - name: "get_product"
    description: "Retrieves a single product from Shopify by product ID"
  - name: "delete_product"
    description: "Deletes a product from Shopify, including all associated variants and media"
  - name: "get_inventory_level"
    description: "Gets the inventory level for a specific inventory item"
  - name: "adjust_inventory"
    description: "Adjusts inventory levels for a specific inventory item"
  - name: "update_inventory_tracking" 
    description: "Enable or disable inventory tracking for a specific inventory item"
  - name: "get_variant_inventory_item"
    description: "Gets the inventory item ID for a specific product variant"
