name: "SharePoint guMCP Server"
icon: "assets/icon.png"
description: "Interact with SharePoint for list management, document handling, user administration, file management, and site page management"
documentation_path: "README.md"
tools:
  # USER MANAGEMENT TOOLS
  - name: "get_users"
    description: "Get all users from Microsoft 365 with filtering and pagination options"
  # LIST MANAGEMENT TOOLS
  - name: "list_site_lists"
    description: "List all lists in a SharePoint site"
  - name: "create_list"
    description: "Create a new list in SharePoint"
  - name: "get_list"
    description: "Get details of a SharePoint list by ID or title"
  # LIST ITEM MANAGEMENT TOOLS
  - name: "create_list_item"
    description: "Create a new item in a SharePoint list"
  - name: "get_list_item"
    description: "Get details of a specific item in a SharePoint list"
  - name: "get_list_items"
    description: "Get all items from a SharePoint list with filtering and sorting options"
  - name: "delete_list_item"
    description: "Delete a specific item from a SharePoint list"
  - name: "update_list_item"
    description: "Update fields of an existing item in a SharePoint list"
  # FILE MANAGEMENT TOOLS
  - name: "download_file"
    description: "Download a file from the current user's OneDrive"
  - name: "create_folder"
    description: "Create a new folder in the current user's OneDrive"
  - name: "upload_file"
    description: "Upload a file to the current user's OneDrive"
  # SITE PAGE MANAGEMENT TOOLS
  - name: "create_site_page"
    description: "Create a new SharePoint site page"
  - name: "get_site_page"
    description: "Get details of a specific page in a SharePoint site"
  - name: "list_site_pages"
    description: "List all pages in a SharePoint site"
  # SITE INFORMATION TOOLS
  - name: "get_site_info"
    description: "Get metadata and information about a SharePoint site"
  - name: "search_sites"
    description: "Search for SharePoint sites by keyword"