name: "Google Meet guMCP Server"
icon: "assets/icon.png"
description: "Interact with Google Meet using the Google Calendar API"
documentation_path: "README.md"
tools:
  - name: "create_meeting"
    description: "Create a new meeting"
  - name: "add_attendees"
    description: "Add attendees to a meeting."
  - name: "fetch_meetings_by_date"
    description: "Fetch all meetings for a given date."
  - name: "get_meeting_details"
    description: "Get details of a meeting by meeting id."
  - name: "update_meeting"
    description: "Update a meeting by meeting id."
  - name: "delete_meeting"
    description: "Delete a meeting by meeting id."