name: "Word guMCP Server"
icon: "assets/icon.png"
description: "Interact with Microsoft Word documents stored in OneDrive"
documentation_path: "README.md"
tools:
  - name: "list_documents"
    description: "List Word documents from OneDrive"
  - name: "create_document"
    description: "Create a new Word document in OneDrive"
  - name: "read_document"
    description: "Read text content from a Word document"
  - name: "write_document"
    description: "Append content to an existing Word document"
  - name: "search_documents"
    description: "Search for Word documents by content"
  - name: "download_document"
    description: "Get a download URL for a Word document"
  - name: "delete_document"
    description: "Delete a Word document from OneDrive"
