name: "Webflow guMCP Server"
icon: "assets/icon.png"
description: "Interact with Webflow sites, forms, collections, and users"
documentation_path: "README.md"
tools:
  - name: "get_authorized_user"
    description: "Get information about the authorized Webflow user"
  - name: "list_sites"
    description: "List all sites the provided access token is able to access"
  - name: "get_site"
    description: "Get details of a specific site by its ID"
  - name: "get_custom_domains"
    description: "Get a list of all custom domains related to a site"
  - name: "list_forms"
    description: "List forms for a given site"
  - name: "list_form_submissions"
    description: "List form submissions for a given form"
  - name: "get_form_submission"
    description: "Get information about a specific form submission"
  - name: "list_form_submissions_by_site"
    description: "List form submissions for a given site"
  - name: "delete_form_submission"
    description: "Delete a form submission"
  - name: "list_pages"
    description: "List all pages for a site"
  - name: "get_page_metadata"
    description: "Get metadata information for a single page"
  - name: "get_page_content"
    description: "Get content from a static page"
  - name: "list_collections"
    description: "List all Collections within a Site"
  - name: "get_collection"
    description: "Get the full details of a collection from its ID"
  - name: "delete_collection"
    description: "Delete a collection using its ID"
  - name: "create_collection"
    description: "Create a Collection for a site"
  - name: "list_collection_items_staging"
    description: "List all Items within a Collection"
  - name: "get_collection_item_staging"
    description: "Get details of a selected Collection Item"
  - name: "update_collection_item_staging"
    description: "Update a selected Item in a Collection"
  - name: "update_collection_items_staging"
    description: "Update a single item or multiple items in a Collection"
  - name: "create_collection_item_staging"
    description: "Create Item in a Collection"
  - name: "delete_collection_item_staging"
    description: "Delete an item from a collection"
  - name: "delete_collection_items_staging"
    description: "Delete Items from a Collection"
  - name: "list_users"
    description: "Get a list of users for a site"
  - name: "get_user"
    description: "Get a User by ID"
  - name: "delete_user"
    description: "Delete a User by ID"
  - name: "invite_user"
    description: "Create and invite a user with an email address"
