name: "Firecrawl guMCP Server"
icon: "assets/icon.png"
description: "Web scraping, crawling, and data extraction using Firecrawl API"
documentation_path: "README.md"
tools:
  - name: "scrape_url"
    description: "Scrape a single URL with Firecrawl"
  - name: "batch_scrape"
    description: "Scrape multiple URLs in a batch with Firecrawl"
  - name: "get_batch_status"
    description: "Check the status of a batch scrape job"
  - name: "get_batch_error"
    description: "Get errors from a batch scrape job"
  - name: "crawl_website"
    description: "Crawl a website starting from a base URL"
  - name: "get_crawl_status"
    description: "Check the status of a crawl job"
  - name: "cancel_crawl"
    description: "Cancel an ongoing crawl job"
  - name: "map_website"
    description: "Map all URLs on a website"
  - name: "extract_data"
    description: "Extract structured data from URLs"
  - name: "get_extract_status"
    description: "Check the status of an extract job"
  - name: "search"
    description: "Search the web and get full page content for search results"
  - name: "check_credit_usage"
    description: "Check your Firecrawl credit usage"
