name: dropbox
description: A server for interacting with Dropbox API to manage files and folders
documentation_path: "README.md"
tools:
  - name: list_files
    description: List files or folders in a specific directory in Dropbox
  - name: upload_file
    description: Upload a file to a specific directory in Dropbox
  - name: create_folder
    description: Create a folder in a specific directory in Dropbox
  - name: delete
    description: Delete a file or folder from a specific directory in Dropbox
  - name: download
    description: Download a file from a specific directory in Dropbox
  - name: search
    description: Search for a file or a folder in Dropbox
  - name: move
    description: Move a file or a folder to a specific directory in Dropbox
  - name: get_user_info
    description: Get information about the current user
  - name: get_file_metadata
    description: Get metadata/information about a file in Dropbox

