name: "Lemlist guMCP Server"
icon: "assets/icon.png"
description: "Interact with Lemlist for campaign management, lead enrichment, scheduling, and outreach automation."
documentation_path: "README.md"
tools:
  # Team & Account
  - name: "get_team"
    description: "Get the team information."
  - name: "get_senders"
    description: "Get the list of senders."
  - name: "get_credits"
    description: "Get the credits information."
  - name: "get_user"
    description: "Get the user information by user ID."
  # Campaign Management
  - name: "get_all_campaigns"
    description: "Retrieve a paginated list of Lemlist campaigns. Supports sorting and pagination."
  - name: "get_campaign"
    description: "Retrieve the details of a specific Lemlist campaign by its campaignId."
  - name: "create_campaign"
    description: "Create a new campaign in Lemlist with optional name. Returns campaign, sequence, and schedule IDs."
  - name: "update_campaign"
    description: "Update the configuration of a Lemlist campaign by campaignId. Supports updating name and multiple campaign settings."
  - name: "pause_lemlist_campaign"
    description: "Pause a running Lemlist campaign by its campaignId. If the campaign is not running, no action is taken."
  # Campaign Export
  - name: "start_lemlist_campaign_export"
    description: "Initiate an asynchronous export of campaign statistics. Returns export ID for status tracking."
  - name: "get_campaign_export_status"
    description: "Check the status of an asynchronous campaign export in Lemlist. Returns export status and CSV URL if available."
  - name: "export_lemlist_campaign"
    description: "Set an email address to receive the download link for a Lemlist campaign export when it's done."
  # Schedules
  - name: "get_all_schedules"
    description: "Retrieve all schedules associated with a Lemlist team, with pagination and sorting options."
  - name: "get_schedule"
    description: "Retrieve the details of a specific Lemlist schedule by its scheduleId."
  - name: "get_campaign_schedules"
    description: "Retrieve all schedule objects linked to a specific Lemlist campaign by campaignId."
  - name: "create_schedule"
    description: "Create a new schedule in Lemlist. Supports custom name, delay, timezone, start/end times, and active weekdays."
  - name: "update_schedule"
    description: "Update an existing Lemlist schedule by scheduleId. Supports updating name, delay, timezone, start/end times, and weekdays."
  - name: "delete_schedule"
    description: "Delete a specific schedule in Lemlist by its scheduleId."
  - name: "associate_schedule_with_campaign"
    description: "Associate a schedule with a specific Lemlist campaign using campaignId and scheduleId."
  # Leads
  - name: "create_lead_in_campaign"
    description: "Add a lead to a specific Lemlist campaign. Supports deduplication, email verification, LinkedIn enrichment, phone finding, and custom lead data."
  - name: "delete_lead"
    description: "Delete a lead from a specific Lemlist campaign by campaignId and leadId (email address). All information, including statistics, will be permanently deleted."
  - name: "mark_lead_as_interested_all_campaigns"
    description: "Mark a specific lead as interested in all campaigns using their email address. Stops their campaign sequence."
  - name: "mark_lead_as_not_interested_all_campaigns"
    description: "Mark a specific lead as not interested in all campaigns using their email address. Stops their campaign sequence."
  - name: "mark_lead_as_interested_in_campaign"
    description: "Mark a specific lead as interested in a specific Lemlist campaign using their email address. Stops their campaign sequence."
  - name: "mark_lead_as_not_interested_in_campaign"
    description: "Mark a specific lead as not interested in a specific Lemlist campaign using their email address. Stops their campaign sequence."
  # Unsubscribes
  - name: "get_all_unsubscribes"
    description: "Retrieve a paginated list of all unsubscribed people from Lemlist. Supports offset and limit for pagination."
  - name: "export_unsubscribes"
    description: "Download a CSV file containing all unsubscribed email addresses from Lemlist."
  - name: "add_unsubscribe"
    description: "Add an email address or domain to Lemlist's unsubscribed list. Domains must start with @ (e.g. @domain.com)."
  - name: "delete_unsubscribe"
    description: "Delete an email address or domain from Lemlist's unsubscribed list. Domains must start with @ (e.g. @domain.com)."
  # Database
  - name: "get_database_filters"
    description: "Retrieve all available Lemlist database filters for constructing advanced queries."
