name: "Canva guMCP Server"
icon: "assets/icon.png"
description: "Interact with Canva designs, folders, and comments using the Canva API"
documentation_path: "README.md"
tools:
  - name: "get_user_profile"
    description: "Get the current user's profile information including display name"
  - name: "get_user_details"
    description: "Get the current user's details including user ID and team ID"
  - name: "get_thread"
    description: "Get metadata for a comment thread on a design"
  - name: "create_reply"
    description: "Reply to a comment on a design"
  - name: "create_thread"
    description: "Create a new comment thread on a design"
  - name: "list_replies"
    description: "List the replies to a comment on a design"
  - name: "get_reply"
    description: "Get a specific reply to a comment"
  - name: "get_design"
    description: "Get the metadata for one of the user's designs"
  - name: "list_designs"
    description: "List all the user's designs with optional filtering and sorting"
  - name: "create_design"
    description: "Create a new Canva design with optional type, asset, and title"
  - name: "create_folder"
    description: "Create a new folder in the user's Projects"
  - name: "get_folder"
    description: "Get the metadata for a folder"
  - name: "update_folder"
    description: "Update a folder's metadata (name)"
  - name: "delete_folder"
    description: "Delete a folder and move its contents to Trash"
