name: "Reddit MCP Server"
icon: "assets/icon.png"
description: "Interact with Reddit using the Reddit API"
documentation_path: "README.md"
tools:
  - name: "retrieve_reddit_post"
    description: "Fetch top posts in a subreddit with optional size limit."
  - name: "get_reddit_post_details"
    description: "Get detailed content about a specific Reddit post"
  - name: "create_reddit_post"
    description: "Create a new Reddit post"
  - name: "fetch_post_comments"
    description: "Fetch the comments of a reddit post."
  - name: "edit_reddit_post"
    description: "Edit a specific Reddit post"
  - name: "edit_reddit_comment"
    description: "Edit a specific Reddit comment"
  - name: "delete_reddit_post"
    description: "Delete a specific Reddit post"
  - name: "delete_reddit_comment"
    description: "Delete a specific Reddit comment"
