name: "Intercom guMCP Server"
icon: "assets/icon.png"
description: "Interact with Intercom customer messaging and support platform"
documentation_path: "README.md"
tools:
  - name: "search_contacts"
    description: "Search for contacts in Intercom by name or email"
  - name: "create_contact"
    description: "Create a new contact in Intercom"
  - name: "create_conversation"
    description: "Create a new conversation in Intercom"
  - name: "reply_to_conversation"
    description: "Reply to an existing conversation in Intercom"
  - name: "add_tags_to_conversation"
    description: "Add tags to an existing conversation"
  - name: "remove_tags_from_conversation"
    description: "Remove tags from an existing conversation"
  - name: "list_admins"
    description: "List all admins/team members in the Intercom workspace"
  - name: "search_companies"
    description: "Search for companies in Intercom"
  - name: "create_company"
    description: "Create a new company in Intercom"
  - name: "associate_contact_with_company"
    description: "Associate a contact with a company"
  - name: "list_articles"
    description: "List help center articles"
  - name: "search_articles"
    description: "Search help center articles"
  - name: "get_article"
    description: "Get a specific help center article by ID"
  - name: "create_article"
    description: "Create a new help center article"
  - name: "list_tickets"
    description: "List support tickets in Intercom"
  - name: "get_ticket"
    description: "Get details of a specific support ticket"
  - name: "create_ticket"
    description: "Create a new support ticket in Intercom"
  - name: "update_ticket"
    description: "Update an existing support ticket in Intercom"
  - name: "add_comment_to_ticket"
    description: "Add a comment to an existing support ticket"
  - name: "list_ticket_types"
    description: "List all available ticket types in the Intercom workspace"
