name: "HubSpot guMCP Server"
icon: "assets/icon.png"
description: "Interact with HubSpot CRM for managing contacts, companies, and deals"
documentation_path: "README.md"
tools:
  - name: "list_contacts"
    description: "List HubSpot contacts with optional filtering"
  - name: "create_contact"
    description: "Create a new HubSpot contact"
  - name: "update_contact"
    description: "Update an existing HubSpot contact"
  - name: "search_contacts"
    description: "Search for HubSpot contacts using advanced filters"
  - name: "list_companies"
    description: "List HubSpot companies with optional filtering"
  - name: "create_company"
    description: "Create a new HubSpot company"
  - name: "update_company"
    description: "Update an existing HubSpot company"
  - name: "list_deals"
    description: "List HubSpot deals with optional filtering"
  - name: "create_deal"
    description: "Create a new HubSpot deal"
  - name: "update_deal"
    description: "Update an existing HubSpot deal"
  - name: "get_engagements"
    description: "Get engagement data (calls, emails, meetings) for a contact"
  - name: "send_email"
    description: "Send an email to a HubSpot contact"
