name: "Zoom GuMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with Zoom Meetings API"
documentation_path: "README.md"
tools:
  - name: "create_meeting"
    description: "Create a new Zoom meeting"
  - name: "update_meeting"
    description: "Update an existing Zoom meeting"
  - name: "get_meeting"
    description: "Get details of a Zoom meeting"
  - name: "list_meetings"
    description: "List all Zoom meetings"
  - name: "list_upcoming_meetings"
    description: "List all upcoming Zoom meetings"
  - name: "list_all_recordings"
    description: "List all recordings"
  - name: "get_meeting_recordings"
    description: "Get recordings for a specific meeting"
  - name: "get_meeting_participant_reports"
    description: "Get participant reports for a meeting"
  - name: "add_attendees"
    description: "Add attendees to a Zoom meeting"
  - name: "fetch_meetings_by_date"
    description: "Fetch all Zoom meetings for a given date"
  - name: "delete_meeting"
    description: "Delete a Zoom meeting"
