name: "Zoom GuMCP Server"
icon: "assets/icon.png"
description: "Server for interacting with Zoom Meetings API"
documentation_path: "README.md"
tools:
  - name: "zoom_create_a_meeting"
    description: "Create a new Zoom meeting"
  - name: "zoom_update_a_meeting"
    description: "Update an existing Zoom meeting"
  - name: "zoom_get_a_meeting"
    description: "Get details of a Zoom meeting"
  - name: "zoom_list_meetings"
    description: "List all Zoom meetings"
  - name: "zoom_list_upcoming_meetings"
    description: "List all upcoming Zoom meetings"
  - name: "zoom_list_all_recordings"
    description: "List all recordings"
  - name: "zoom_get_meeting_recordings"
    description: "Get recordings for a specific meeting"
  - name: "zoom_get_meeting_participant_reports"
    description: "Get participant reports for a meeting"
  - name: "zoom_add_attendees"
    description: "Add attendees to a Zoom meeting"
  - name: "zoom_fetch_meetings_by_date"
    description: "Fetch all Zoom meetings for a given date"
  - name: "zoom_delete_meeting"
    description: "Delete a Zoom meeting"
