name: "Google Maps guMCP Server"
icon: "assets/icon.png"
description: "Interact with Google Maps using the Google Maps API"
documentation_path: "README.md"
tools:
  - name: "address_to_coordinates"
    description: "Get the coordinates of an address"
  - name: "coordinates_to_address"
    description: "Get the address of a set of coordinates"
  - name: "maps_search_places"
    description: "Search for places around a set of coordinates"
  - name: "maps_place_details"
    description: "Get details about a place"
  - name: "get_place_reviews"
    description: "Retrieve channel metadata including title and description"
  - name: "maps_distance_matrix"
    description: "Get the distance and duration between two sets of coordinates"
  - name: "maps_elevation"
    description: "Get the elevation of a set of coordinates"
  - name: "maps_directions"
    description: "Get directions between two sets of coordinates"
