name: "Google Forms guMCP Server"
icon: "assets/icon.png"
description: "Interact with Google Forms using the Google Forms API"
documentation_path: "README.md"
tools:
  - name: "list_forms"
    description: "List all forms."
  - name: "create_form"
    description: "Creates a new form."
  - name: "get_form"
    description: "Retrieves an existing form by its ID."
  - name: "update_form"
    description: "Updates an existing form by its ID."
  - name: "move_form_to_trash"
    description: "Removes a form and moves it to trash."
  - name: "list_responses"
    description: "Retrieves a list of responses."
  - name: "get_response"
    description: "Retrieves the details of a response by its ID."
  - name: "search_forms"
    description: "Retrieves a list of forms by name."
  - name: "add_question"
    description: "Add a question to an existing Google Form."
  - name: "delete_item"
    description: "Deletes an item (question) from an existing Google Form."
