name: "Cal.com guMCP Server"
icon: "assets/icon.png"
description: "Manage your Cal.com scheduling and bookings"
documentation_path: "README.md"
tools:
  - name: "get_me"
    description: "Get your Cal.com user profile information"
  - name: "get_event_types"
    description: "Get all event types from Cal.com"
  - name: "get_booking" 
    description: "Get a booking from Cal.com by its unique ID"
  - name: "reschedule_booking"
    description: "Reschedule an existing booking to a new time"
  - name: "cancel_booking"
    description: "Cancel an existing booking"
  - name: "confirm_booking"
    description: "Confirm a pending booking"
  - name: "decline_booking"
    description: "Decline a pending booking"
  - name: "create_booking"
    description: "Create a booking in Cal.com"
  - name: "get_bookings"
    description: "Get all bookings from Cal.com"
  - name: "get_schedules"
    description: "Get all schedules from the authenticated user in Cal.com"
  - name: "get_availability"
    description: "Get available time slots for scheduling"
