name: "X guMCP Server"
icon: "assets/icon.png"
description: "Interact with X (formerly Twitter) for searching tweets, posting, and user information"
documentation_path: "README.md"
tools:
  - name: "search_recent_tweet"
    description: "Search for recent tweets (last 7 days) matching a query"
  - name: "get_user_profile"
    description: "Get an X user's profile information"
  - name: "get_user_posts"
    description: "Get a user's posts (tweets created by the user)"
  - name: "get_user_home_timeline" 
    description: "Get a user's home timeline (tweets from users they follow)"
  - name: "get_user_mentions"
    description: "Get tweets that mention a specific user"
  - name: "get_tweet_by_id"
    description: "Look up a specific tweet by its ID"
  - name: "create_tweet"
    description: "Create a new tweet on behalf of the authenticated user"
  - name: "delete_tweet"
    description: "Delete a tweet by ID"
