name: "Reducto guMCP Server"
icon: "assets/icon.png"
description: "Document processing and data extraction API"
documentation_path: "README.md"
tools:
  - name: "get_version"
    description: "Get the Reducto API version"
  - name: "upload_document"
    description: "Upload a document to Reducto"
  - name: "parse_document"
    description: "Parse a document using OCR"
  - name: "parse_document_async"
    description: "Parse a document asynchronously"
  - name: "get_job_status"
    description: "Check the status of a job"
  - name: "cancel_job"
    description: "Cancel a running job"
  - name: "split_document"
    description: "Split a document into sections"
  - name: "split_document_async"
    description: "Split a document into sections asynchronously"
  - name: "extract_data"
    description: "Extract structured data from a document"
  - name: "extract_data_async"
    description: "Extract structured data asynchronously"
  - name: "configure_webhook"
    description: "Configure the webhook portal"
