name: "Pipedrive guMCP Server"
icon: "assets/icon.png"
description: "Interact with Pipedrive CRM using the Pipedrive API"
documentation_path: "README.md"
tools:
  # Activity Operations
  - name: "create_activity"
    description: "Create a new activity in Pipedrive"
  - name: "get_activity"
    description: "Get a specific activity from Pipedrive"
  - name: "update_activity"
    description: "Update an activity in Pipedrive"
  - name: "delete_activity"
    description: "Delete an activity from Pipedrive"
  # Deal Operations
  - name: "create_deal"
    description: "Create a new deal in Pipedrive"
  - name: "get_deal"
    description: "Get a specific deal from Pipedrive"
  - name: "update_deal"
    description: "Update a deal in Pipedrive"
  - name: "delete_deal"
    description: "Delete a deal from Pipedrive"
  # Lead Operations
  - name: "create_lead"
    description: "Create a new lead in Pipedrive"
  - name: "get_lead"
    description: "Get a specific lead from Pipedrive"
  - name: "delete_lead"
    description: "Delete a lead from Pipedrive"
  # Note Operations
  - name: "create_note"
    description: "Create a new note in Pipedrive"
  - name: "get_note"
    description: "Get a specific note from Pipedrive"
  - name: "update_note"
    description: "Update a note in Pipedrive"
  - name: "delete_note"
    description: "Delete a note from Pipedrive"
  # Person Operations
  - name: "create_person"
    description: "Create a new person in Pipedrive"
  - name: "get_person"
    description: "Get a specific person from Pipedrive"
  - name: "update_person"
    description: "Update a person in Pipedrive"
  - name: "delete_person"
    description: "Delete a person from Pipedrive"
  # Product Operations
  - name: "create_product"
    description: "Create a new product in Pipedrive"
  - name: "get_product"
    description: "Get a specific product from Pipedrive"
  - name: "update_product"
    description: "Update a product in Pipedrive"
  - name: "delete_product"
    description: "Delete a product from Pipedrive"
  # Organization Operations
  - name: "create_organization"
    description: "Create a new organization in Pipedrive"
  - name: "get_organization"
    description: "Get a specific organization from Pipedrive"
  - name: "update_organization"
    description: "Update an organization in Pipedrive"
  - name: "delete_organization"
    description: "Delete an organization from Pipedrive"
  # User Operations
  - name: "get_all_users"
    description: "Get all users from Pipedrive" 